# Generated by Django 5.0.6 on 2024-05-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_history',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
