# Generated by Django 5.0.6 on 2024-06-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
