from langchain_google_vertexai import ChatVertexAI, VertexAIEmbeddings, HarmBlockThreshold, HarmCategory
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts import ChatPromptTemplate
from dotenv import dotenv_values
from common.logger import logger
import os
import re


env = dotenv_values()
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = env["GOOGLE_APPLICATION_CREDENTIALS"]


class BaseLLMAgent():
    """
    BaseLLMAgent class for implementing a Retrieval-Augmented Generation system.

    This class verifies the model name during instantiation and initializes a basic chain containing an
    initial prompt template, an LLM and a string output parser.
    """

    def __init__(self, model_name: str = 'gemini-1.5-pro', initial_system_prompt: str = None):
        """
        Initializes the BaseLLMAgent.

        Args:
        model_name (str, optional): The name of the language model to use. Defaults to 'gemini-1.5-pro'.
        initial_system_prompt (str, optional): The initial prompt for the system. Defaults to None.
        """

        self.model_configs = {
            "model_name": model_name,
            "temperature": 0.2,
            "safety_settings": {
                HarmCategory.HARM_CATEGORY_UNSPECIFIED: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
            },
            "max_tokens": 2048,
        }
        self.history = []
        self.vertex_ai_embeddings = VertexAIEmbeddings(
            model_name="textembedding-gecko@latest"
        )
        self.llm = ChatVertexAI(**self.model_configs)
        self.initial_system_prompt = initial_system_prompt
        self.str_output_parser = StrOutputParser()

    def clean_response(self, response: str):
        """
        Cleans the response by removing unnecessary characters and multiple whitespaces.

        Args:
        response (str): The response to clean.

        Returns:
        str: The cleaned response.
        """
        # response = response.encode('ascii', 'ignore').decode('ascii')
        response = re.sub('\s+', ' ', response)
        return response

    def prompt(self, message: str):
        """
        Processes the user prompt and generates a response using the language model.

        Args:
        message (str): The user prompt.

        Returns:
        str: The response generated by the language model.
        """
        message_history = [
            ("system", self.initial_system_prompt),
            *self.transform_history(self.history, output_type="langchain"),
            ("human", "{input}")
        ]

        self.qa = ChatPromptTemplate.from_messages(message_history)
        self.chain = self.qa | self.llm | self.str_output_parser

        logger.debug(f"Base LLM Received: {message}")
        response = self.chain.invoke({"input": message})
        logger.debug(f"Base LLM Response: {response}")

        self.history.append({
            "role": "human",
            "message": message
        })
        self.history.append({
            "role": "ai",
            "message": response
        })

        logger.debug(f"Final response: {response}")
        response = self.clean_response(response)
        return response

    def stream_prompt(self, message: str):
        """
        Processes the user prompt and generates a response using the language model.

        Args:
        message (str): The user prompt.

        Yields:
        str: The response generated by the language model.
        """
        message_history = [
            ("system", self.initial_system_prompt),
            *self.transform_history(self.history, output_type="langchain"),
            ("human", "{input}")
        ]

        self.qa = ChatPromptTemplate.from_messages(message_history)
        self.chain = self.qa | self.llm | self.str_output_parser

        logger.debug(f"Base LLM Received: {message}")
        complete_response = ""

        for chunk in self.chain.stream({"input": message}):
            logger.debug(f"Base LLM Chunk: {chunk}")
            complete_response += chunk
            yield chunk

        self.history.append({
            "role": "human",
            "message": message
        })
        self.history.append({
            "role": "ai",
            "message": complete_response
        })

        logger.debug(f"Final response: {complete_response}")
        complete_response = self.clean_response(complete_response)
        return complete_response

    def transform_history(self, history, output_type):
        """
        Transforms the chat history into the specified output format.

        Args:
        history (list): The chat history.
        output_type (str): The desired output format.

        Returns:
        list: The transformed chat history.
        """
        transformed_history = []

        if output_type == "langchain":
            for message in history:
                role = message["role"]
                text = message["message"]

                if role == "human":
                    transformed_history.append(("user", text))
                elif role == "ai":
                    transformed_history.append(("ai", text))
                elif role == "system":
                    transformed_history.append(("system", text))
                else:
                    raise ValueError(f"Invalid role {role} in chat history.")

        return transformed_history[-20:]

    def clear_history(self):
        """
        Clears the chat history.
        """
        self.history = []
        logger.debug("Chat history cleared.")
        return
