# Generated by Django 5.0.6 on 2024-06-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('POL', 'Póliza General'), ('CAL', 'Clausula Adicional'), ('CAD', 'Clausula Adicional'), ('COP', 'Clausula Opcional'), ('CUG', 'Clausula de Uso General')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('insurance_company', models.CharField(max_length=100)),
                ('deposit_date', models.DateField()),
                ('linked_policies', models.JSONField(blank=True, default=list)),
                ('prohibition_resolution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('authorization_resolution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('topics', models.TextField()),
                ('page_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('char_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
