# Generated by Django 5.0.6 on 2024-06-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_policy_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='char_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='page_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='word_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
