# Generated by Django 5.0.6 on 2024-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_policy_char_count_alter_policy_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='linked_policies',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
