# Generated by Django 5.0.6 on 2024-06-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_policy_linked_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_prohibited',
            field=models.BooleanField(default=False),
        ),
    ]
