# Generated by Django 5.0.6 on 2024-06-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_policy_is_prohibited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='linked_policies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
